### ISSUE TITLE
How to implement XMPPNotificationClient

### ISSUE THREAD

**Issue by IamDeshRaj** [huberflores/XMPPNotificationClient#1]
Hey Guys, I have to implement XMPPNotificationClient notification for my application. Please Anyone can guide me how to register the device into XMPP and how to push message to XMPPNotificationServer. As I'm very new to Android Development.

**Comment by huberflores** [comment]
what is the problem you are facing? as stated the server relies on a XMPP server as broker to distribute the messages. So, you just have to put a valid JID to the server, and to each mobile you just assign its respective JID. The link of the client is also in the README

**Comment by anassabrd** [comment]
Hey, first i want to think you for the sample, it's easy to implement, i just want to understand the changes that i've to make in:
1- server side (Openfire in my case), precisely the server.properties file, i've changed the domain but i don't know what do you mean by server attribute, also is there any changes to make in the shell script?
2- client app, is there any changes to make? and what do you mean exactly by Recipient, is it the ip address?
Thinks again
